-- AlterTable
ALTER TABLE "requestSensorInfo" ADD COLUMN     "base_value" DOUBLE PRECISION,
ADD COLUMN     "last_value" DOUBLE PRECISION,
ALTER COLUMN "add_zero" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "logical_zero" SET DATA TYPE DOUBLE PRECISION;
